<EntryScreen>:
    GridLayout:
        cols: 2
        rows: 2
        padding: 20
        spacing: 10

        Button:
            text: "Create List"
            disabled: True

        Button:
            text: "Import List"
            disabled: False

        Button:
            text: "Create With Friends"
            disabled: False

        Button:
            text: "My Lists"
            disabled: True